-- Home-grown funnel + retention tracking, built on the existing visitor
-- tracking tables. Alternative to a third-party analytics tool: logs which
-- views a session visits, tracks per-session duration, and computes D1
-- retention — all readable from the admin panel.

-- Session duration: visitor_sessions already gets one row per (session_id,
-- visited_date) via trackVisit(); last_seen is now touched by heartbeat()
-- so duration = last_seen - created_at.
ALTER TABLE visitor_sessions ADD COLUMN IF NOT EXISTS last_seen timestamptz DEFAULT now();

-- Per-session view log — one row per in-app navigation, mirrors the
-- client's view_changed event so we can see where sessions actually go.
CREATE TABLE IF NOT EXISTS session_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL,
  user_id uuid REFERENCES auth.users(id),
  view text NOT NULL,
  visited_date date NOT NULL DEFAULT (now() AT TIME ZONE 'utc')::date,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS session_views_date_idx ON session_views (visited_date);
CREATE INDEX IF NOT EXISTS session_views_session_idx ON session_views (session_id, visited_date);

ALTER TABLE session_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "session_views_insert" ON session_views;
CREATE POLICY "session_views_insert"
  ON session_views
  AS PERMISSIVE
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

GRANT INSERT ON session_views TO anon, authenticated;
GRANT SELECT ON session_views TO service_role;

-- =====================================================================
-- Admin RPC: today's (or any date's) funnel — session counts per view,
-- how many sessions actually started a game, and average duration.
-- =====================================================================
CREATE OR REPLACE FUNCTION get_admin_funnel(p_date date DEFAULT CURRENT_DATE)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_total_sessions  int;
  v_view_counts     json;
  v_played_sessions int;
  v_avg_duration    numeric;
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT COUNT(DISTINCT session_id) INTO v_total_sessions
    FROM visitor_sessions WHERE visited_date = p_date;

  SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) INTO v_view_counts
  FROM (
    SELECT view, COUNT(DISTINCT session_id) AS sessions
    FROM session_views
    WHERE visited_date = p_date
    GROUP BY view
    ORDER BY sessions DESC
  ) t;

  SELECT COUNT(DISTINCT session_id) INTO v_played_sessions
    FROM session_views
    WHERE visited_date = p_date AND view LIKE 'game\_%' ESCAPE '\';

  SELECT AVG(EXTRACT(EPOCH FROM (last_seen - created_at))) INTO v_avg_duration
    FROM visitor_sessions
    WHERE visited_date = p_date AND last_seen > created_at;

  RETURN json_build_object(
    'date', p_date,
    'total_sessions', COALESCE(v_total_sessions, 0),
    'view_counts', v_view_counts,
    'played_sessions', COALESCE(v_played_sessions, 0),
    'avg_duration_seconds', ROUND(COALESCE(v_avg_duration, 0))
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION get_admin_funnel(date) TO authenticated;

-- =====================================================================
-- Admin RPC: D1 retention — for each of the last N days, how many
-- sessions from that day's cohort came back the next day.
-- =====================================================================
CREATE OR REPLACE FUNCTION get_admin_retention(p_days int DEFAULT 14)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_result json;
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT COALESCE(json_agg(row_to_json(t)), '[]'::json) INTO v_result
  FROM (
    SELECT
      d.visited_date AS date,
      COUNT(DISTINCT d.session_id) AS cohort_size,
      COUNT(DISTINCT d.session_id) FILTER (
        WHERE EXISTS (
          SELECT 1 FROM visitor_sessions n
          WHERE n.session_id = d.session_id AND n.visited_date = d.visited_date + 1
        )
      ) AS returned_next_day
    FROM visitor_sessions d
    WHERE d.visited_date >= CURRENT_DATE - (p_days || ' days')::interval
      AND d.visited_date < CURRENT_DATE
    GROUP BY d.visited_date
    ORDER BY d.visited_date
  ) t;

  RETURN v_result;
END;
$function$;

GRANT EXECUTE ON FUNCTION get_admin_retention(int) TO authenticated;
