-- =====================================================================
-- Admin heart monitoring
-- =====================================================================
-- Adds an append-only event stream for member heart activity and admin RPCs
-- for the dashboard. Guest hearts are local-only by design, so this captures
-- authenticated members only.

CREATE TABLE IF NOT EXISTS public.heart_events (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type     text NOT NULL CHECK (event_type IN (
    'consume',
    'refund',
    'blocked_no_hearts',
    'buy_infinite',
    'refill_full',
    'infinite_start'
  )),
  mode           text,
  hearts_before  int,
  hearts_after   int,
  infinite_until timestamptz,
  metadata       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.heart_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin read heart events" ON public.heart_events;
CREATE POLICY "admin read heart events" ON public.heart_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

CREATE INDEX IF NOT EXISTS heart_events_created_at_idx
  ON public.heart_events (created_at DESC);

CREATE INDEX IF NOT EXISTS heart_events_user_created_idx
  ON public.heart_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS heart_events_type_created_idx
  ON public.heart_events (event_type, created_at DESC);

CREATE OR REPLACE FUNCTION public._log_heart_event(
  p_user_id uuid,
  p_event_type text,
  p_mode text DEFAULT NULL,
  p_hearts_before int DEFAULT NULL,
  p_hearts_after int DEFAULT NULL,
  p_infinite_until timestamptz DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  INSERT INTO public.heart_events (
    user_id,
    event_type,
    mode,
    hearts_before,
    hearts_after,
    infinite_until,
    metadata
  )
  VALUES (
    p_user_id,
    p_event_type,
    p_mode,
    p_hearts_before,
    p_hearts_after,
    p_infinite_until,
    COALESCE(p_metadata, '{}'::jsonb)
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public._log_heart_event(uuid, text, text, int, int, timestamptz, jsonb) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.consume_heart(p_mode text DEFAULT NULL)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid      uuid := auth.uid();
  v_row      public.user_hearts;
  v_before   int;
  v_infinite boolean;
BEGIN
  IF v_uid IS NULL THEN
    RETURN json_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;
  v_row := _refresh_hearts(v_uid);
  v_before := v_row.hearts;
  v_infinite := v_row.infinite_until IS NOT NULL AND v_row.infinite_until > now();

  IF v_infinite THEN
    PERFORM public._log_heart_event(v_uid, 'infinite_start', p_mode, v_before, v_row.hearts, v_row.infinite_until);
    RETURN json_build_object('ok', true, 'consumed', false, 'hearts', v_row.hearts,
                             'infinite', true, 'infinite_until', v_row.infinite_until);
  END IF;

  IF v_row.hearts <= 0 THEN
    PERFORM public._log_heart_event(v_uid, 'blocked_no_hearts', p_mode, v_before, 0, NULL);
    RETURN json_build_object('ok', false, 'reason', 'no_hearts', 'hearts', 0,
                             'consumed', false, 'infinite', false,
                             'last_regen_at', v_row.last_regen_at);
  END IF;

  UPDATE user_hearts
    SET hearts = hearts - 1,
        last_regen_at = CASE WHEN hearts = 5 THEN now() ELSE last_regen_at END,
        updated_at = now()
    WHERE user_id = v_uid
    RETURNING * INTO v_row;

  PERFORM public._log_heart_event(v_uid, 'consume', p_mode, v_before, v_row.hearts, NULL);

  RETURN json_build_object('ok', true, 'consumed', true, 'hearts', v_row.hearts,
                           'infinite', false, 'last_regen_at', v_row.last_regen_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.refund_heart()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_row public.user_hearts;
  v_before int;
BEGIN
  IF v_uid IS NULL THEN
    RETURN json_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;
  v_row := _refresh_hearts(v_uid);
  v_before := v_row.hearts;
  UPDATE user_hearts SET hearts = LEAST(5, hearts + 1), updated_at = now()
    WHERE user_id = v_uid
    RETURNING * INTO v_row;
  PERFORM public._log_heart_event(v_uid, 'refund', NULL, v_before, v_row.hearts, v_row.infinite_until);
  RETURN json_build_object('ok', true, 'hearts', v_row.hearts);
END;
$$;

CREATE OR REPLACE FUNCTION public.buy_infinite_hearts(p_hours int)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid   uuid := auth.uid();
  v_price int;
  v_spend jsonb;
  v_base  timestamptz;
  v_row   public.user_hearts;
  v_before int;
BEGIN
  IF v_uid IS NULL THEN
    RETURN json_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;

  v_price := CASE p_hours
    WHEN 1 THEN 800
    WHEN 2 THEN 1400
    WHEN 3 THEN 1900
    WHEN 5 THEN 2800
    ELSE NULL
  END;
  IF v_price IS NULL THEN
    RETURN json_build_object('ok', false, 'reason', 'bad_hours');
  END IF;

  v_spend := spend_coins(v_uid, v_price, 'infinite_hearts',
                         jsonb_build_object('hours', p_hours));
  IF NOT COALESCE((v_spend->>'ok')::boolean, false) THEN
    RETURN json_build_object('ok', false,
                             'reason', COALESCE(v_spend->>'reason', 'insufficient_coins'),
                             'balance', (v_spend->>'balance')::int);
  END IF;

  v_row := _refresh_hearts(v_uid);
  v_before := v_row.hearts;
  v_base := GREATEST(now(), COALESCE(v_row.infinite_until, now()));
  UPDATE user_hearts
    SET infinite_until = v_base + (p_hours || ' hours')::interval, updated_at = now()
    WHERE user_id = v_uid
    RETURNING * INTO v_row;

  PERFORM public._log_heart_event(
    v_uid,
    'buy_infinite',
    NULL,
    v_before,
    v_row.hearts,
    v_row.infinite_until,
    jsonb_build_object('hours', p_hours, 'price', v_price, 'balance', (v_spend->>'balance')::int)
  );

  RETURN json_build_object('ok', true, 'infinite_until', v_row.infinite_until,
                           'hearts', v_row.hearts, 'balance', (v_spend->>'balance')::int);
END;
$$;

CREATE OR REPLACE FUNCTION public.refill_hearts_full()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_row public.user_hearts;
  v_before int;
BEGIN
  IF v_uid IS NULL THEN
    RETURN json_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;
  v_row := _refresh_hearts(v_uid);
  v_before := v_row.hearts;
  UPDATE user_hearts SET hearts = 5, last_regen_at = now(), updated_at = now()
    WHERE user_id = v_uid
    RETURNING * INTO v_row;
  PERFORM public._log_heart_event(v_uid, 'refill_full', NULL, v_before, v_row.hearts, v_row.infinite_until);
  RETURN json_build_object('ok', true, 'hearts', v_row.hearts);
END;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_hearts_overview()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_result json;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
  ) THEN
    RETURN json_build_object('error', 'forbidden');
  END IF;

  SELECT json_build_object(
    'current', (
      SELECT json_build_object(
        'tracked_members', COALESCE(COUNT(*), 0),
        'full_hearts', COALESCE(COUNT(*) FILTER (WHERE hearts = 5), 0),
        'zero_hearts', COALESCE(COUNT(*) FILTER (WHERE hearts = 0), 0),
        'low_hearts', COALESCE(COUNT(*) FILTER (WHERE hearts BETWEEN 1 AND 2), 0),
        'avg_hearts', COALESCE(ROUND(AVG(hearts)::numeric, 2), 0),
        'infinite_active', COALESCE(COUNT(*) FILTER (WHERE infinite_until > now()), 0)
      )
      FROM public.user_hearts
    ),
    'events_today', (
      SELECT json_build_object(
        'consumes', COALESCE(COUNT(*) FILTER (WHERE event_type = 'consume'), 0),
        'refunds', COALESCE(COUNT(*) FILTER (WHERE event_type = 'refund'), 0),
        'blocked', COALESCE(COUNT(*) FILTER (WHERE event_type = 'blocked_no_hearts'), 0),
        'infinite_starts', COALESCE(COUNT(*) FILTER (WHERE event_type = 'infinite_start'), 0),
        'buff_purchases', COALESCE(COUNT(*) FILTER (WHERE event_type = 'buy_infinite'), 0),
        'unique_users', COALESCE(COUNT(DISTINCT user_id), 0)
      )
      FROM public.heart_events
      WHERE created_at >= date_trunc('day', now() AT TIME ZONE 'Asia/Bangkok') AT TIME ZONE 'Asia/Bangkok'
    ),
    'by_mode_today', COALESCE((
      SELECT json_agg(row_to_json(m) ORDER BY m.consumes DESC, m.mode)
      FROM (
        SELECT
          COALESCE(mode, 'unknown') AS mode,
          COUNT(*) FILTER (WHERE event_type = 'consume') AS consumes,
          COUNT(*) FILTER (WHERE event_type = 'blocked_no_hearts') AS blocked,
          COUNT(*) FILTER (WHERE event_type = 'infinite_start') AS infinite_starts,
          COUNT(DISTINCT user_id) AS users
        FROM public.heart_events
        WHERE created_at >= date_trunc('day', now() AT TIME ZONE 'Asia/Bangkok') AT TIME ZONE 'Asia/Bangkok'
          AND event_type IN ('consume', 'blocked_no_hearts', 'infinite_start')
        GROUP BY COALESCE(mode, 'unknown')
      ) m
    ), '[]'::json),
    'current_rows', COALESCE((
      SELECT json_agg(row_to_json(r) ORDER BY r.hearts ASC, r.infinite_active DESC, r.updated_at DESC)
      FROM (
        SELECT
          h.user_id,
          COALESCE(p.display_name, p.username, 'Member') AS display_name,
          p.username,
          h.hearts,
          h.last_regen_at,
          h.infinite_until,
          h.infinite_until > now() AS infinite_active,
          h.updated_at
        FROM public.user_hearts h
        LEFT JOIN public.profiles p ON p.id = h.user_id
        ORDER BY h.hearts ASC, h.infinite_until > now() DESC, h.updated_at DESC
        LIMIT 50
      ) r
    ), '[]'::json)
  )
  INTO v_result;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_heart_events(p_limit int DEFAULT 100)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'
  ) THEN
    RETURN json_build_object('error', 'forbidden');
  END IF;

  RETURN COALESCE((
    SELECT json_agg(row_to_json(r) ORDER BY r.created_at DESC)
    FROM (
      SELECT
        e.id,
        e.user_id,
        COALESCE(p.display_name, p.username, 'Member') AS display_name,
        p.username,
        e.event_type,
        e.mode,
        e.hearts_before,
        e.hearts_after,
        e.infinite_until,
        e.metadata,
        e.created_at
      FROM public.heart_events e
      LEFT JOIN public.profiles p ON p.id = e.user_id
      ORDER BY e.created_at DESC
      LIMIT LEAST(GREATEST(COALESCE(p_limit, 100), 1), 500)
    ) r
  ), '[]'::json);
END;
$$;

GRANT EXECUTE ON FUNCTION public.consume_heart(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_heart() TO authenticated;
GRANT EXECUTE ON FUNCTION public.buy_infinite_hearts(int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refill_hearts_full() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_hearts_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_admin_heart_events(int) TO authenticated;
